name: push to gas-estimates
on:
  push:
    branches:
      - test-ci-spreadsheet

jobs:
  push-to-gas-estimates:
    name: Save gas estimates
    runs-on: ubuntu-latest
    environment: gas-estimation
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10.x'
      - name: Estimate gas
        env:
          SAVE_GAS_REPORT: '1'
          MNEMONIC_KEY: '${{ secrets.MNEMONIC_KEY }}'
          ETHERSCAN_API_KEY: '${{ secrets.ETHERSCAN_API_KEY }}'
          INFURA_KEY: '${{ secrets.INFURA_KEY }}'
          ALCHEMY_KEY: '${{ secrets.ALCHEMY_KEY }}'
          CMC_KEY: '${{ secrets.CMC_KEY }}'
        run: |
          yarn
          yarn compile
          yarn test
          yarn test utils/gas-estimator.ts
          mkdir -p gas/$GITHUB_SHA gas/HEAD
          mv gas-reporter.txt gas/$GITHUB_SHA/
          mv gas-estimation.csv gas/$GITHUB_SHA/
          cp gas/$GITHUB_SHA/* gas/HEAD/
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gas
          git commit -m "Gas estimations for commit $GITHUB_SHA"
          git push https://github.com/$GITHUB_REPOSITORY $GITHUB_REF:gas-estimates
