name: push to gas-estimates
on:
  push:
    branches:
      - test-ci-spreadsheet

jobs:
  push-to-gas-estimates:
    name: Save gas estimates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10.x'
      - name: estimate gas
        env:
          SAVE_GAS_REPORT: 1
        run: |
          yarn
          yarn compile
          yarn test
          yarn test utils/gas-estimator.ts
      - name: commit and push
        run: |
          mkdir -p gas/$GITHUB_SHA gas/HEAD
          mv gas-reporter.txt gas/$GITHUB_SHA/
          mv gas-estimation.csv gas/$GITHUB_SHA/
          cp gas/$GITHUB_SHA/* gas/HEAD/
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gas
          git commit -m "Gas estimations for commit $GITHUB_SHA"
          git push https://github.com/$GITHUB.REPOSITORY $GITHUB_REF:gas-estimates
