name: push to gas-estimates
on:
  push:
    branches:
      - test-ci-spreadsheet

jobs:
  push-to-gas-estimates:
    name: Save gas estimates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: gas-estimation
        env:
          SAVE_GAS_REPORT: 1
        run: |
          yarn
          yarn test
          yarn test utils/gas-estimator.ts
      - run: |
          mkdir -p gas/$GITHUB_REF gas/HEAD
          mv gas-reporter.txt gas/$GITHUB_REF/
          mv gas-estimation.csv gas/$GITHUB_REF/
          cp gas/$GITHUB_REF/* gas/HEAD/
          git add gas
          git commit -m "Gas estimations for commit $GITHUB_REF"
